### PR TITLE
Migrate from CRA to Vite + SWC

### LINKED ISSUE #1: Create React App is deprecated
noticed you used Create React app(CRA), and wanted to point out that CRA was deprecated in 2023 due to it being incompatible with new tooling & slow as it relied on webpack. 

Here are some articles on the matter:
1. https://dev.to/ag2byte/create-react-app-is-officially-dead-h7o
2. https://www.theodinproject.com/lessons/node-path-react-new-setting-up-a-react-environment
3. https://dev.to/clumsycoder/is-create-react-app-really-dead-what-are-other-options-1j39

The recommendation I have seen most popular is [Vite](https://vitejs.dev/), I have personally used vite, and it is super similar to CRA + it comes with some really nice features out of the box like [env vars and modes](https://vitejs.dev/guide/env-and-mode.html).

That being said, you might also be interested in [Svelte](https://svelte.dev/). I dont know much about Svelte but I have heard its the leading tech in web apps. Of course you dont want to just join the hypetrain, but something to consider.

I dont mind helping out with a migration from CRA to Vite or some other tooling for React and or Svelte, but just wanted to let you know!

### PR DESCRIPTION
**Pull request by hnucamendi**
Resolves #1 

# Why
CRA is deprecated and has degraded development and built performance

# What
Migrate to the modern standard Vite + the SWC transpiler
This PR includes:
1. Reorganizing file structure
2. Removing CRA specific packages
3. adding Vite config + Vite and SWC packages
4. Adding Env files for development

## File Structure

Not much needs to change in the actual file structure, but you will notice:
1. The `index.html` file is now in the root
2. the index.js file is now `main.jsx`
3. all files that have React components must have the file extension `.jsx`
4. more .env files have been added

## SWC
[SWC](https://swc.rs/) is a JavaScript compiler and bundler written in rust, and is much faster than legacy [Babel](https://babeljs.io/). This app is net new and really has no need for the Babel ecosystem, so why not take advantage of the performance boosts

## Env FIles
Vite has the idea of [Modes](https://vitejs.dev/guide/env-and-mode.html#modes) and we can use Modes to create .env files based on different build enviornments / local. Super useful and I wanted to include some information on how to take advantage of these modes
https://vitejs.dev/guide/env-and-mode.html#env-files
https://vitejs.dev/guide/env-and-mode.html#env-variables 

## Note
Changes have not been tested thoroughly, should make time to make sure all is working fine.

Screenshot after running `npm run dev` to load in development mode
Screenshot 2024-01-27 124943

### CODE REVIEW

**Comment by hnucamendi** [comment]
Merge conflicts seem to be due to the fact that all files containing React components must be renamed to have the `.jsx` extension

**Comment by michael-ortiz** [comment]
Thank you @hnucamendi for putting this! I can see some really nice performance improvements already!

**Comment by hnucamendi** [comment]
> Thank you @hnucamendi for putting this! I can see some really nice performance improvements already!

Nice! No problem, Ill keep an eye on any other issues that come up here. A couple things I noticed just looking around are:
1. Could add more testing
2. Lambda API is running on version of nod that is in maintenance mode Version 20 is the latest until October of this year
3. Add E2E Frontend tests with something like [cypress](https://www.cypress.io/) 

I would like to get some testing in so we can confidently upgrade Node version as they come out in the future.

**Comment by michael-ortiz** [comment]
@hnucamendi  Yes! We can upgrade the lambda runtime for sure! Adding cypress test might be useful as well!

Quick note, I am having issues reading env variables with Vite. 

Fore example, I try to use this and it returns undefined.

```
    console.log(import.meta.env.VITE_API_ENDPOINT);
```

Were you able to have success on your PR?

**Comment by hnucamendi** [comment]
> @hnucamendi Yes! We can upgrade the lambda runtime for sure! Adding cypress test might be useful as well!
> 
> Quick note, I am having issues reading env variables with Vite.
> 
> Fore example, I try to use this and it returns undefined.
> 
> ```
>     console.log(import.meta.env.VITE_API_ENDPOINT);
> ```
> 
> Were you able to have success on your PR?

@michael-ortiz Oh your right I accidentally put the .env files under ./react/src/ we should move them to be at the root of the react directory ./react/

**Pull request merged**
